// client/src/routes/AuthFlowInfo.svelte
<script>
  import { authError, authSuccess } from '../store/user';
  import { onDestroy } from 'svelte';
  import { Alert } from 'flowbite-svelte';

  onDestroy(() => {
    authError.set(null);
    authSuccess.set(null);
  });
</script>

<div>
  {#if $authError}
    <Alert color="red">{$authError}</Alert>
  {/if}
  {#if $authSuccess}
    <Alert color="green">{$authSuccess}</Alert>
  {/if}
</div>

// client/src/routes/AuthFlowInfo.tsx
import React from 'react';
import { useAuthStatus } from '../store/user';
import { Alert } from 'flowbite-react';

const UserAlerts = ({success, error}) => {
  return (
    <div>
      {success && (
        <Alert color="green">{success}</Alert>
      )}
      {error && (
        <Alert color="red">{error}</Alert>
      )}
    </div>
  );
};

export default UserAlerts;
