// client/src/routes/Login.svelte
<!-- A Svelte login component that prompts the user for an email and password -->
<script>
  import AuthFlowInfo from './AuthFlowInfo.svelte';

  import { onMount } from 'svelte';
  import { createEventDispatcher } from 'svelte';
  import { login, authError, authSuccess } from '../store/user';

  const dispatch = createEventDispatcher();

  let email = '';
  let password = '';

  async function doLogin() {
    await login(email, password);
  }

  // focus the email input on mount
  onMount(() => {
    document.querySelector('input').focus();
  });
</script>

<div>
  <h1>Log in</h1>

  <label for="email">Email</label>
  <input id="email" type="email" bind:value={email} />

  <label for="password">Password</label>
  <input id="password" type="password" bind:value={password} />

  <button on:click={doLogin}>Log in</button>
  <AuthFlowInfo />
</div>

// client/src/routes/Login.tsx
import React from 'react';
import { useEffect, useState } from 'react';
import AuthFlowInfo from './AuthFlowInfo';

import { useLogin } from '../store/user';
import { Label, TextInput, Button } from 'flowbite-react';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const doLogin = useLogin()[0];

  // focus the email input on mount
  useEffect(() => {
    document.querySelector('input')?.focus();
  }, []);

  return (
    <div>
      <h2 className="text-center">
        Log in
      </h2>

      <div className="mb-6">
        <Label htmlFor="email">Email</Label>
        <TextInput id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
      </div>

      <div className="mb-6">
        <Label htmlFor="password">Password</Label>
        <TextInput id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
      </div>

      <div className="mb-6">
        <Button onClick={() => doLogin(email, password)}>Log in</Button>
      </div>

      {/* <AuthFlowInfo /> */}
    </div>
  );
};

export default Login;
