// client/src/App.tsx
import React from "react";
import { useState, useEffect } from "react";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import Markdown from "markdown-to-jsx";

import Navbar from "./components/Navbar";
import Login from "./routes/Login";
import Register from "./routes/Register";
import Home from "./routes/Home";
import Evidence from "./routes/Evidence";
import { NavLink } from "./types/nav";
import { ctfg } from "./service";
import { useUser } from "./store/user";
import { usePages } from "./store/pages";
import useDarkMode from "use-dark-mode";
import { NextUIProvider, createTheme } from "@nextui-org/react";
import "react-toastify/dist/ReactToastify.min.css";
import { ToastContainer } from "react-toastify";

interface Props {}

function App() {
	const [links, setLinks] = useState<NavLink[]>([]);
	const [user, setUser, logout] = useUser();
	const [pages, setPages] = usePages();
	const navBarLinks: NavLink[] = [
		{
			label: "Home",
			to: "/",
			Component: Home,
			showWhenAuthed: true,
		},
		{
			label: "Evidence",
			to: "/evidence",
			Component: Evidence,
			showWhenAuthed: true,
			hideWhenUnauthed: true,
		},
		{
			label: "Login",
			to: "/login",
			Component: Login,
			showWhenAuthed: false,
		},
		{
			label: "Sign Up",
			to: "/register",
			Component: Register,
			showWhenAuthed: false,
		},
	];

	useEffect(() => {
		async function fetchCurrentUser() {
			try {
				setLinks(navBarLinks);
				if (!user) {
					return;
				}
				const resp = await ctfg.CurrentUser({});
				console.log(resp)
				setUser({
					username: resp.username,
					type: resp.userRole,
				});
				setPages(resp.pages);
			} catch (e) {
				console.log(e);
			}
		}
		fetchCurrentUser();
	}, []);

	const lightTheme = createTheme({
		type: "light",
	});

	const darkTheme = createTheme({
		type: "dark",
	});
	const darkMode = useDarkMode(false);

	return (
		<NextUIProvider theme={darkMode.value ? darkTheme : lightTheme}>
			<main>
				<Router>
					<Navbar links={links} />
					<Routes>
						{links.map((link) => (
							<Route key={link.to} path={link.to} Component={link.Component} />
						))}
						{pages && (
							<>
								{pages.map((page) => (
									<Route key={page.route} path={page.route}>
										<Markdown>{page.content}</Markdown>
									</Route>
								))}
							</>
						)}
					</Routes>
				</Router>
			</main>
			<ToastContainer />
		</NextUIProvider>
	);
}

export default App;

// client/src/App.svelte
<script lang="ts">
    import { Router, Route } from "svelte-routing";
    import snarkdown from 'snarkdown';

    import Navbar from "./components/Navbar.svelte";
    import Login from "./routes/Login.svelte";
    import Register from "./routes/Register.svelte";
    import Home from "./routes/Home.svelte";
    import type { NavLink } from "./types/nav";
    import { onMount } from "svelte";
    import { ctfg } from "./service";
    import { user } from "./store/user";
    import Evidence from "./routes/Evidence.svelte";
    import { pages } from "./store/pages";

    onMount(async () => {
		try {
			const resp = await ctfg.CurrentUser({});
            user.set({
                username: resp.username,
            });
            pages.set(resp.pages);
		} catch (e) {
            console.log(e);
		}
    });

    const links: NavLink[] = [
        {
            label: "Home",
            to: "/",
            Component: Home,
            showWhenAuthed: true,
        },
        {
            label: "Evidence",
            to: "/evidence",
            Component: Evidence,
            showWhenAuthed: true,
            hideWhenUnauthed: true,
        },
        {
            label: "Login",
            to: "/login",
            Component: Login,
            showWhenAuthed: false,
        },
        {
            label: "Register",
            to: "/register",
            Component: Register,
            showWhenAuthed: false,
        },
    ];
</script>

<main>
    <Router>
        <Navbar {links} />
        <div class="max-w-2xl px-6 py-16 mx-auto space-y-12">
            {#each links as link}
                <Route path={link.to} component={link.Component} />
            {/each}
            {#if $pages}
                {#each $pages as page}
                    <Route path={page.route}>
                        {@html snarkdown(page.content)}
                    </Route>
                {/each}
            {/if}
        </div>
    </Router>
</main>
