// client/src/components/Navbar.svelte.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { user } from "../store/user";
import type { NavLink } from "../types/nav";
import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from "flowbite-svelte";
import { Button } from "flowbite-svelte";

interface NavbarProps {
  links: NavLink[];
}

const NavbarComponent = ({ links }: NavbarProps) => {
  const [path, updatePath] = useState(window.location.pathname);
  const userLoggedIn = user !== null;

  const logout = () => {
    document.cookie = "";
    user.set(null);
  };

  return (
    <Navbar>
      <NavBrand>CTFg</NavBrand>
      <NavHamburger />
      <NavUl>
        {links.map((l) => {
          if (
            (userLoggedIn && l.showWhenAuthed) ||
            (!userLoggedIn && !l.hideWhenUnauthed)
          ) {
            return (
              <NavLi active={l.to === path}>
                <Link
                  onClick={() => updatePath(l.to)}
                  to={l.to}
                >
                  <span>{l.label}</span>
                </Link>
              </NavLi>
            );
          }
        })}
        {user && (
          <>
            <NavLi>{user.username}</NavLi>
            <NavLi onClick={logout}>Logout</NavLi>
          </>
        )}
      </NavUl>
    </Navbar>
  );
};

export default NavbarComponent;

// client/src/components/Navbar.svelte
<script lang="ts">
    import { derived } from "svelte/store";
    import { Link } from "svelte-routing";
    import { user } from "../store/user";
    import type { NavLink } from "../types/nav";
    import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte'
    import { Button } from 'flowbite-svelte'

    export let links: NavLink[] = [];
    let path: string = window.location.pathname;

    const updatePath = (newPath: string) => (path = newPath);

    const userLoggedIn = derived(user, user => user !== null);

    const logout = () => {
        document.cookie = '';
        user.set(null);
    }
</script>

<Navbar let:hidden let:toggle>
    <NavBrand>CTFg</NavBrand>
    <NavHamburger on:click={toggle} />
    <NavUl {hidden}>
        {#each links as l}
            {#if ($userLoggedIn && l.showWhenAuthed) || (!$userLoggedIn && !l.hideWhenUnauthed)}
                <NavLi active={l.to == path}>
                    <Link
                        on:click={() => updatePath(l.to)}
                        to={l.to}
                    >
                        <span>{l.label}</span>
                    </Link>
                </NavLi>
            {/if}
        {/each}
        {#if $user}
            <NavLi>{$user.username}</NavLi>
            <NavLi on:click={logout}>Logout</NavLi>
        {/if}
    </NavUl>
</Navbar>
